# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d770760902c7216969badf4fc7cd1c357b1cdf7ed455c69370179c7ab83fcb2b7c001e19a172c1bfa12f39d0897dcf8b2e455221bcbebda0ff10ed50f31f118

test:
  secret_key_base: 1567b35b7e520c8589ac31bf9b4d0a1f5a996a7a28b9820ae1f07c8b6425ffc37003e9fee9f49e4c08cffe276e15524af6a0297b25b8a60823096e0633296b81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
